# Generated by Django 3.2.7 on 2021-11-01 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='covidmonitor.country')),
            ],
        ),
        migrations.CreateModel(
            name='Recovered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time_series_num', models.IntegerField(blank=True, null=True)),
                ('daily_reports_num', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='recovered', max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='covidmonitor.country')),
                ('province_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='covidmonitor.provincestate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time_series_num', models.IntegerField(blank=True, null=True)),
                ('daily_reports_num', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='deaths', max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='covidmonitor.country')),
                ('province_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='covidmonitor.provincestate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Confirmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time_series_num', models.IntegerField(blank=True, null=True)),
                ('daily_reports_num', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='confirmed', max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='covidmonitor.country')),
                ('province_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='covidmonitor.provincestate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time_series_num', models.IntegerField(blank=True, null=True)),
                ('daily_reports_num', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='active', max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='covidmonitor.country')),
                ('province_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='covidmonitor.provincestate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
