# Generated by Django 3.2.7 on 2021-11-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidmonitor', '0002_auto_20211101_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidmonitordate',
            old_name='time_series_num',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='covidmonitordate',
            name='daily_reports_num',
        ),
    ]
