# Generated by Django 3.2.7 on 2021-11-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidmonitor', '0003_auto_20211102_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidmonitordate',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='covidmonitordate',
            name='province_state',
            field=models.CharField(max_length=255),
        ),
    ]
