# Generated by Django 3.2.7 on 2021-11-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidmonitor', '0004_auto_20211102_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='ProvinceState',
        ),
    ]
