# Generated by Django 3.2.7 on 2021-11-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidmonitor', '0005_auto_20211103_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CovidMonitorDate',
            new_name='CovMonitorDate',
        ),
    ]
