# Generated by Django 3.2.7 on 2021-11-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidmonitor', '0006_rename_covidmonitordate_covmonitordate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CovMonitorDate',
            new_name='CovidMonitorDate',
        ),
    ]
