# Generated by Django 3.2.7 on 2021-11-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidmonitor', '0007_rename_covmonitordate_covidmonitordate'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidmonitordate',
            name='combined_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='covidmonitordate',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='covidmonitordate',
            name='province_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='covidmonitordate',
            unique_together={('title', 'date', 'country', 'province_state', 'combined_key')},
        ),
    ]
