# Generated by Django 3.2.7 on 2021-11-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidmonitor', '0008_auto_20211103_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidmonitordate',
            name='date',
            field=models.DateField(),
        ),
    ]
