# Generated by Django 3.2.7 on 2021-11-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidmonitor', '0009_alter_covidmonitordate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidmonitordate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
