# Generated by Django 3.2.7 on 2021-11-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidmonitor', '0010_alter_covidmonitordate_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidmonitordate',
            name='internal_combined_key',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='covidmonitordate',
            unique_together={('title', 'date', 'country', 'province_state', 'combined_key', 'internal_combined_key')},
        ),
    ]
