# Generated by Django 3.2.7 on 2021-11-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidmonitor', '0011_auto_20211106_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidmonitordate',
            name='internal_combined_key',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='covidmonitordate',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='covidmonitordate',
            index=models.Index(fields=['internal_combined_key'], name='covidmonito_interna_d216e2_idx'),
        ),
    ]
